In [1]:
#1. Create NumPy Array and Convert 1D Array to 2D
import numpy as np
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

arr2d = arr.reshape(2, 3)

print("Original Array:")
print(arr)

print("\n2D Array:")
print(arr2d)

Original Array:
[1 2 3 4 5 6]

2D Array:
[[1 2 3]
 [4 5 6]]


In [2]:
#2. Print Array Attributes
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Data Type:", arr.dtype)
print("Item Size:", arr.itemsize)

Shape: (2, 3)
Dimension: 2
Data Type: int64
Item Size: 8


In [3]:
#3. Create a 3×3 NumPy Array of All 9
arr = np.full((3, 3), 9)
print("3×3 Array of All 9:")
print(arr)

3×3 Array of All 9:
[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [4]:
#4. Create a 1D Array of 10 Evenly Spaced Values Between 25 and 125
import numpy as np

arr = np.linspace(25, 125, 10)

print(arr)

[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [5]:
#5. Convert a Python List into a NumPy Array
import numpy as np

lst = [10, 20, 30, 40, 50]

arr = np.array(lst)

print(arr)

[10 20 30 40 50]


In [6]:
#6. Reverse a 1D NumPy Array
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

rev = arr[::-1]

print(rev)

[50 40 30 20 10]


In [8]:
#7. Create a 4×4×3 Array and Extract Value at Second Set, First Row and Last Column

import numpy as np

arr = np.arange(48).reshape(4, 4, 3)

print(arr)

value = arr[1, 0, 2]

print("\nRequired Value =", value)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]

Required Value = 14


In [7]:
#8. Create a 4×4 Array and Extract Odd Rows and Even Columns
import numpy as np

arr = np.arange(1, 17).reshape(4, 4)

print("Original Array:")
print(arr)

result = arr[::2, 1::2]

print("\nOdd Rows and Even Columns:")
print(result)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Odd Rows and Even Columns:
[[ 2  4]
 [10 12]]


In [9]:
#9. Slice the First Two Rows and First Two Columns of Second Set from a 4×4×3 Array
import numpy as np

arr = np.arange(48).reshape(4, 4, 3)

result = arr[1, :2, :2]

print(result)

[[12 13]
 [15 16]]


In [10]:
#10. Replace All Odd Numbers with -1 Using For Loop
import numpy as np

arr = np.array([[23, 56, 78, 93],
                [71, 82, 13, 24]])

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if arr[i][j] % 2 != 0:
            arr[i][j] = -1

print(arr)

[[-1 56 78 -1]
 [-1 82 -1 24]]


In [11]:
#11. Get Indices of Non-Zero Elements
import numpy as np

arr = np.array([1, 0, 2, 0, 3, 0, 4])

indices = np.nonzero(arr)

print(indices)

(array([0, 2, 4, 6]),)


In [12]:
#12. Add Two NumPy Arrays Element-wise
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([5, 15, 25])

result = arr1 + arr2

print(result)

[15 35 55]


In [13]:
#13. Multiply Two NumPy Arrays Element-wise
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([5, 15, 25])

result = arr1 * arr2

print(result)

[ 50 300 750]


In [14]:
#14. Compute Dot Product
import numpy as np

arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

dot_product = np.dot(arr1, arr2)

print("Dot Product =", dot_product)

Dot Product = 1875
