In [ ]:
# 1) Combining a One-Dimensional and a Two-Dimensional NumPy Array
import numpy as np
one = np.array([1, 2, 3])

two = np.array([[4, 5, 6],
                [7, 8, 9]])

combined_array = np.vstack((one, two))
print("Combined Array:")
print(combined_array)

Combined Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# 2) Flatten a 2D NumPy Array into 1D Array
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
flattened_array = arr_2d.flatten()
print("\nFlattened Array:")
print(flattened_array)


Flattened Array:
[1 2 3 4 5 6 7 8 9]


In [2]:
import numpy as np

#3) Reverse a NumPy Array
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print("\nReversed Array:")
print(reversed_arr)


Reversed Array:
[5 4 3 2 1]


In [3]:
#4) Practice Operations
#(a) Maximum Value
arr = np.array([[1, -2, 3],
                         [-4, 5, -6],
                         [7, -8, 9]])
max_value = np.max(arr)
print("\nMaximum Value:", max_value)

#(b) Minimum Value
min_value = np.min(arr)
print("Minimum Value:", min_value)

#(c) Number of Rows and Columns
num_rows, num_cols = arr.shape
print("Number of Rows:", num_rows)
print("Number of Columns:", num_cols)

#(d) Select Elements

import numpy as np

arr = np.array([[10,20,30],
                [40,50,60]])

print("All Elements:")
print(arr)

print("Specific Element:")
print(arr[1,2])

#(e) Sum of 2D Array Using For Loop
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6]])

total = 0

for row in arr:
    for element in row:
        total += element

print("Sum =", total)

#(f) Add, Subtract, Multiply, Divide Arrays
import numpy as np
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[7,8,9],
                 [10,11,12]])

print("Addition =", arr1 + arr2)
print("Subtraction =", arr1 - arr2)
print("Multiplication =", arr1 * arr2)
print("Division =", arr1 / arr2)








Maximum Value: 9
Minimum Value: -8
Number of Rows: 3
Number of Columns: 3
All Elements:
[[10 20 30]
 [40 50 60]]
Specific Element:
60
Sum = 21
Addition = [[ 8 10 12]
 [14 16 18]]
Subtraction = [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication = [[ 7 16 27]
 [40 55 72]]
Division = [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [5]:
# 5) Iterate 3D Array Using For Loop and nditer
import numpy as np

arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print("Using Nested Loops:")

for i in arr:
    for j in i:
        for k in j:
            print(k)

print("\nUsing nditer:")
for x in np.nditer(arr):
    print(x)
    


Using Nested Loops:
1
2
3
4
5
6
7
8

Using nditer:
1
2
3
4
5
6
7
8


In [8]:
#6) Average, Mean, Median and Mode of Two NumPy 2D Arrays

import numpy as np
import scipy as sp

arr1 = np.array([[10,20,30],
                 [40,50,60]])

arr2 = np.array([[5,15,25],
                 [35,45,55]])

# Average
average = (arr1 + arr2) / 2

print("Average:")
print(average)

# Combine arrays
combined = np.concatenate((arr1, arr2))

# Mean
print("\nMean =", np.mean(combined))

# Median
print("Median =", np.median(combined))

# Mode
mode = sp.stats.mode(combined, axis=None)

print("Mode =", mode.mode)

Average:
[[ 7.5 17.5 27.5]
 [37.5 47.5 57.5]]

Mean = 32.5
Median = 32.5
Mode = 5
